import Head from 'next/head';
import Link from 'next/link';

import { MongoClient } from 'mongodb';
import Card from '@/components/ui/Card';

export default function Home(props) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<title>Message Manager</title>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Messages</h1>
			{props.messages.map((message) => (
				<Card key={message.id}>
					<h2> {message.postedAt}</h2>
					<p>{message.message}</p>
					<cite>{message.author}</cite>
					<p>
						<Link href={message.postUrl.post}>Post</Link>
					</p>
					<p>
						<Link href={message.postUrl.story}>Story</Link>
					</p>
				</Card>
			))}
		</>
	);
}

export async function getServerSideProps() {
	const client = await MongoClient.connect(process.env.MONGODB_URI);
	const db = client.db();

	const messagesCollection = db.collection('messages');

	const messages = await messagesCollection.find().toArray();

	const data = messages.map((message) => ({
		id: message._id.toString(),
		message: message.message,
		author: message.author,
		addedAt: message.addedAt ? message.addedAt.toISOString().slice(0, 10) : '',
		postedAt: message.postedAt
			? message.postedAt.toISOString().slice(0, 10)
			: '',
		post: message.postUrl ? message.postUrl : '',
		postUrl: {
			post: message.postUrl.post ? message.postUrl.post : '',
			story: message.postUrl.story ? message.postUrl.story : '',
		},
	}));

	console.log(data);

	return {
		props: {
			messages: data,
		},
	};
}
